feat: add DN404 attack incident
SunWeb3Sec/DeFiHackLabs pull request #643
Opened 2024-04-29 16:22 UTC by LouisTsai-Csie

```
Ran 1 test for src/test/DN404_exp.sol:DN404
[PASS] testExploit() (gas: 158950)
Logs:
   Attacker USDT Balance Before exploit: 0.000000
   Attacker USDT Balance Before exploit: 169577.736489
```

2024-04-29 22:02 UTC, akshaynexus commented
LGTM

2024-04-30 00:53 UTC, akshaynexus requested changes
Need some changes,overall good

2024-04-30 00:53 UTC, akshaynexus commented on src/test/DN404_exp.sol
> +        emit log_named_decimal_uint(" Attacker USDT Balance Before exploit", IERC20(USDT).balanceOf(address(this)), 6);
Set this log to after exploit

2024-04-30 00:53 UTC, akshaynexus commented on src/test/DN404_exp.sol
> +        uint256 amount = IERC20(FLIX).balanceOf(address(victim));
put this before init,so that its easy to read

2024-04-30 00:53 UTC, akshaynexus commented on README.md
> +
IF not having a link reference remove this part?

2024-04-30 02:34 UTC, LouisTsai-Csie commented
> Need some changes,overall good

@akshaynexus I made some changes according to your suggestion, please take a look. Thank you!

By the way, is there any style guideline for writing the PoCs in this repo, I would like to follow for readability.

2024-04-30 04:18 UTC, akshaynexus commented
I don't think there is one,reason I suggested readability changes is just mostly cause what I tend to prefer whenooking  at contracts at a glance

2024-04-30 11:59 UTC, SunWeb3Sec commented
Corrected some ordering.

2024-04-30 11:59 UTC, merged